# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['gui\\build\\gui.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'backend',
        'backend.config_manager',
        'backend.single_parser',
        'backend.batch_parser',
        'backend.up_manager',
        'backend.valley_scheduler',
        'backend.single_summary_client',
        'backend.time_price_judge',
        'backend.task_queue_manager',
        'pystray',
        'pystray._win32',
        'pystray._base',
        'pystray._util',
        'pystray._util.win32',
        'six',
        'six.moves.queue',
        'PIL.Image',
        'PIL.ImageDraw',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
